### PR TITLE
fix "$pio eval" command

### PR DESCRIPTION
**Pull request by DanVisan**
"$pio eval" command parameters are broken: package name in command does not match the package name in Evaluation.scala

### CODE REVIEW

**Comment by dszeto** [comment]
@tom-chan I think @DanVisan is referring to https://github.com/apache/predictionio-template-attribute-based-classifier/blob/develop/src/main/scala/Evaluation.scala. That is what is being linked from this file right now.

**Comment by tom-chan** [comment]
Got it. In that case do you mind updating other instances of `org.template.classification.` to `org.example.classification.` on this page, as well as docs/manual/source/evaluation/metricbuild.html.md? Thanks.

**Comment by tom-chan** [comment]
Would be great if you also update `docs/manual/source/evaluation/metricbuild.html.md` in the same tutorial series. Thanks!

**Comment by DanVisan** [comment]
@tom-chan i updated `docs/manual/source/evaluation/metricbuild.html.md`. Thanks for noticing!

**Comment by tom-chan** [comment]
LGTM

**Pull request closed without merging**
