### PR TITLE
Update release instructions for PMC

### PR DESCRIPTION
**Pull request by shimamoto**
@dszeto @chanlee514 I modified the release instructions slightly. Can you take a look?

Aside from this, I'm thinking about whether we should improve and automate the release process or not.

### CODE REVIEW

**Comment by dszeto** [comment]
LGTM. Regarding automation, I think we can create scripts for some steps inside the doc.

**Comment by dszeto** [comment]
@shimamoto If you don't mind, please add the missing step that makes a release on JIRA (https://issues.apache.org/jira/projects/PIO?selectedItem=com.atlassian.jira.jira-projects-plugin%3Arelease-page&status=no-filter).

**Comment by shimamoto** [comment]
@dszeto Sure! You mean you want me to add the step that creates a next version after a release?

**Comment by dszeto** [comment]
That would be great too. What I meant was we need to mark the version as released on JIRA. If you don’t see the option in JIRA please let me know.

**Comment by shimamoto** [comment]
I fixed it!

**Comment by dszeto** [comment]
LGTM. Merging. Thank you!

**Pull request closed without merging**
