### PR TITLE
[PIO-172] Add document for upgrading to 0.14.0

### PR DESCRIPTION
**Pull request by shimamoto**
ref #466 

This is a guide which explains how to migrate current indexes by reindexing.

### CODE REVIEW

**Comment by shimamoto** [comment]
@marevol @EmergentOrder @dszeto Do you have time to review this PR?

**Comment by haginot** [comment]
I'll merge it. Any obejection?

**Comment by Wei-1** [comment]
One question, for these documentation changes, we will have another PR to merge these changes to livedoc branch?

**Comment by takezoe** [comment]
Since this document is for the next release, merging to only master would be enough for now. We should merge master to livedoc as a part of the release operation of 0.14.0.

**Comment by haginot** [comment]
This pull request has been merged at commit https://github.com/apache/predictionio/commit/4fe28b9b06521e52ed2e3c70d41a15df605dc660
However, because I pushed it to `git-wip-us.apache.org/repos/asf/predictionio.git` with the wrong pull request ID on the comment, this PR was not been closed automatically.
I'll close this manually.

**Pull request closed without merging**
