### PR TITLE
PIO-161 Spark 2.3.x support

### PR DESCRIPTION
**Pull request by dszeto**

### CODE REVIEW

**Comment by dszeto** [comment]
May one of PMCs please take a look?

**Comment by takezoe** [comment]
Let us look at the result of Travis build first. :-)

**Comment by takezoe** [comment]
Travis has all passed and I checked following things:

- `make-distribution.sh -Dspark.version=2.3.1` on my local PC
- build, train and deploy [text recommendation template](https://predictionio.apache.org/templates/recommendation/quickstart/) with it and MLLib 2.3.1

There wasn't any problem. We can add Spark 2.3.1 support. 👍

**Comment by dszeto** [comment]
Thank you @takezoe! Will merge soon.

**Pull request closed without merging**
